---
# tasks file for switches
- hosts: switches
  gather_facts: no
  tasks:
  - name: Include system
    import_tasks: system.yml

  - name: Include interfaces
    import_tasks: interfaces.yml

  - name: include vlans
    import_tasks: vlans.yml

  - name: Include routing
    import_tasks: routing.yml

  - name: Include dhcp
    import_tasks: dhcp.yml