interfaces:
  - routeros_if: "ether1"
    desc: "WAN"
    nat:
      role: outside
  - routeros_if: "ether2"
    desc: LAN
    ipv4: "10.1.254.1/24"
    nat:
      role: inside
  - routeros_if: "loopback0"
    desc: "Management"
    ipv4: "10.1.2.2"

routes:
  - network: "10.1.0.0/16"
    gateway: "10.1.254.2"
    type: static
