interfaces:
  - routeros_if: "ether1"
    desc: "Uplink"
    ipv4: "10.1.2.3/24"
    pvid: "99"
  - routeros_if: "ether2"
    desc: "ansible server"
    pvid: "10"

routes:
  - gateway: "10.1.2.1"
    type: static

vlans:
 - name: "Clients"
   vid: "10"
 - name: "Management"
   vid: "20"
 - name: "Blackhole"
   vid: "99"

untagged:
  - port: "ether2"
    vlans: "10"

tagged:
  - port: "ether1"
    vlans: "10,20"